name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: ha-ha
        id: joke
        uses: ./.github/actions/joke-action
      - name: joke output
        run: echo "This is the joke ${{ steps.joke.outputs.joke-text}}"